insert into tags (tag_name) values ('MS-DOS');
insert into tags (tag_name) values ('Working Capital Management');
insert into tags (tag_name) values ('fMRI');
insert into tags (tag_name) values ('Slate');
insert into tags (tag_name) values ('Black Belt');
insert into tags (tag_name) values ('Urban Studies');
insert into tags (tag_name) values ('Power Generation');
insert into tags (tag_name) values ('Cisco UCS');
insert into tags (tag_name) values ('Lync');
insert into tags (tag_name) values ('ICP-MS');
insert into tags (tag_name) values ('Broadcast');
insert into tags (tag_name) values ('Data Structures');
insert into tags (tag_name) values ('JMS');
insert into tags (tag_name) values ('Nursing');
insert into tags (tag_name) values ('Geography');
insert into tags (tag_name) values ('Krakatoa');
insert into tags (tag_name) values ('GBS');
insert into tags (tag_name) values ('Aircraft');
insert into tags (tag_name) values ('Spring DM');
insert into tags (tag_name) values ('IKB');
insert into tags (tag_name) values ('FTC');
insert into tags (tag_name) values ('Gas Chromatography');
insert into tags (tag_name) values ('Driving Results');
insert into tags (tag_name) values ('Cytology');
insert into tags (tag_name) values ('Water Treatment');
insert into tags (tag_name) values ('Move Up Buyers');
insert into tags (tag_name) values ('Front Office');
insert into tags (tag_name) values ('Avaya Technologies');
insert into tags (tag_name) values ('User-centered Design');
insert into tags (tag_name) values ('Oleochemicals');
insert into tags (tag_name) values ('Environmental Science');
insert into tags (tag_name) values ('CMake');
insert into tags (tag_name) values ('JCAPS');
insert into tags (tag_name) values ('Childhood Obesity');
insert into tags (tag_name) values ('Kaspersky');
insert into tags (tag_name) values ('Fashion Shows');
insert into tags (tag_name) values ('ODI');
insert into tags (tag_name) values ('EOU');
insert into tags (tag_name) values ('Oracle BPM');
insert into tags (tag_name) values ('Jiu-Jitsu');
insert into tags (tag_name) values ('Title Searches');
insert into tags (tag_name) values ('FFA');
insert into tags (tag_name) values ('Revenue Analysis');
insert into tags (tag_name) values ('Twitter API');
insert into tags (tag_name) values ('JConsole');
insert into tags (tag_name) values ('Recruitment Advertising');
insert into tags (tag_name) values ('HP Blade');
insert into tags (tag_name) values ('MCDST');
insert into tags (tag_name) values ('LLQP');
insert into tags (tag_name) values ('Organizational Effectiveness');
insert into tags (tag_name) values ('Vocal');
insert into tags (tag_name) values ('Kundalini Yoga');
insert into tags (tag_name) values ('Festivals');
insert into tags (tag_name) values ('CTI');
insert into tags (tag_name) values ('Zymography');
insert into tags (tag_name) values ('New Hire Training');
insert into tags (tag_name) values ('Interviewing Skills');
insert into tags (tag_name) values ('Object Oriented Perl');
insert into tags (tag_name) values ('Business Intelligence Tools');
insert into tags (tag_name) values ('Music History');
insert into tags (tag_name) values ('HLA');
insert into tags (tag_name) values ('FX Options');
insert into tags (tag_name) values ('NLTK');
insert into tags (tag_name) values ('Adult Education');
insert into tags (tag_name) values ('CQB');
insert into tags (tag_name) values ('Equipment Installation');
insert into tags (tag_name) values ('Lymphedema');
insert into tags (tag_name) values ('Red Hat Linux');
insert into tags (tag_name) values ('DCF');
insert into tags (tag_name) values ('Summation iBlaze');
insert into tags (tag_name) values ('MFR');
insert into tags (tag_name) values ('Ecotect');
insert into tags (tag_name) values ('Policy Analysis');
insert into tags (tag_name) values ('Spanish');
insert into tags (tag_name) values ('NCFM Certified');
insert into tags (tag_name) values ('JWICS');
insert into tags (tag_name) values ('Medical Illustration');
insert into tags (tag_name) values ('Visual Communication');
insert into tags (tag_name) values ('PIM-DM');
insert into tags (tag_name) values ('Mystery Shopping');
insert into tags (tag_name) values ('GXT');
insert into tags (tag_name) values ('NGOs');
insert into tags (tag_name) values ('Equity Capital Markets');
insert into tags (tag_name) values ('Rx');
insert into tags (tag_name) values ('RDL');
insert into tags (tag_name) values ('Ultrasonic Testing');
insert into tags (tag_name) values ('Newsletters');
insert into tags (tag_name) values ('HIPAA');
insert into tags (tag_name) values ('Keynote');
insert into tags (tag_name) values ('Supply Chain Management');
insert into tags (tag_name) values ('SketchUp');
insert into tags (tag_name) values ('Musical Theatre');
insert into tags (tag_name) values ('Zooarchaeology');
insert into tags (tag_name) values ('Trimble GPS');
insert into tags (tag_name) values ('Cycle Time Reduction');
insert into tags (tag_name) values ('EKG');
insert into tags (tag_name) values ('Unicenter TNG');
insert into tags (tag_name) values ('Dell KACE');
insert into tags (tag_name) values ('MS Integration Services');
insert into tags (tag_name) values ('Epoxy');
