insert into tags (tag_name) values ('product');
insert into tags (tag_name) values ('interface');
insert into tags (tag_name) values ('dedicated');
insert into tags (tag_name) values ('analyzing');
insert into tags (tag_name) values ('customer loyalty');
insert into tags (tag_name) values ('Intuitive');
insert into tags (tag_name) values ('needs-based');
insert into tags (tag_name) values ('responsive');
insert into tags (tag_name) values ('installation');
insert into tags (tag_name) values ('help-desk');
insert into tags (tag_name) values ('Multi-channelled');
insert into tags (tag_name) values ('intranet');
insert into tags (tag_name) values ('clear-thinking');
insert into tags (tag_name) values ('Optional');
insert into tags (tag_name) values ('success');
insert into tags (tag_name) values ('Expanded');
insert into tags (tag_name) values ('Diverse');
insert into tags (tag_name) values ('definition');
insert into tags (tag_name) values ('analyzing');
insert into tags (tag_name) values ('composite');
insert into tags (tag_name) values ('24 hour');
insert into tags (tag_name) values ('logistical');
insert into tags (tag_name) values ('Customer-focused');
insert into tags (tag_name) values ('fresh-thinking');
insert into tags (tag_name) values ('service-desk');
insert into tags (tag_name) values ('Re-contextualized');
insert into tags (tag_name) values ('help-desk');
insert into tags (tag_name) values ('Fully-configurable');
insert into tags (tag_name) values ('Polarised');
insert into tags (tag_name) values ('composite');
insert into tags (tag_name) values ('24 hour');
insert into tags (tag_name) values ('system engine');
insert into tags (tag_name) values ('benchmark');
insert into tags (tag_name) values ('Reverse-engineered');
insert into tags (tag_name) values ('homogeneous');
insert into tags (tag_name) values ('Devolved');
insert into tags (tag_name) values ('budgetary management');
insert into tags (tag_name) values ('Fundamental');
insert into tags (tag_name) values ('Multi-lateral');
insert into tags (tag_name) values ('emulation');
insert into tags (tag_name) values ('attitude-oriented');
insert into tags (tag_name) values ('contextually-based');
insert into tags (tag_name) values ('Synergistic');
insert into tags (tag_name) values ('fresh-thinking');
insert into tags (tag_name) values ('installation');
insert into tags (tag_name) values ('Persevering');
insert into tags (tag_name) values ('project');
insert into tags (tag_name) values ('secondary');
insert into tags (tag_name) values ('even-keeled');
insert into tags (tag_name) values ('Realigned');
insert into tags (tag_name) values ('coherent');
insert into tags (tag_name) values ('De-engineered');
insert into tags (tag_name) values ('artificial intelligence');
insert into tags (tag_name) values ('Up-sized');
insert into tags (tag_name) values ('User-centric');
insert into tags (tag_name) values ('throughput');
insert into tags (tag_name) values ('cohesive');
insert into tags (tag_name) values ('dynamic');
insert into tags (tag_name) values ('Reverse-engineered');
insert into tags (tag_name) values ('alliance');
insert into tags (tag_name) values ('Face to face');
insert into tags (tag_name) values ('web-enabled');
insert into tags (tag_name) values ('Open-architected');
insert into tags (tag_name) values ('Centralized');
insert into tags (tag_name) values ('Extended');
insert into tags (tag_name) values ('optimal');
insert into tags (tag_name) values ('3rd generation');
insert into tags (tag_name) values ('neural-net');
insert into tags (tag_name) values ('encoding');
insert into tags (tag_name) values ('focus group');
insert into tags (tag_name) values ('logistical');
insert into tags (tag_name) values ('Profit-focused');
insert into tags (tag_name) values ('Stand-alone');
insert into tags (tag_name) values ('conglomeration');
insert into tags (tag_name) values ('explicit');
insert into tags (tag_name) values ('Automated');
insert into tags (tag_name) values ('help-desk');
insert into tags (tag_name) values ('Public-key');
insert into tags (tag_name) values ('regional');
insert into tags (tag_name) values ('Quality-focused');
insert into tags (tag_name) values ('orchestration');
insert into tags (tag_name) values ('mission-critical');
insert into tags (tag_name) values ('knowledge user');
insert into tags (tag_name) values ('Networked');
insert into tags (tag_name) values ('logistical');
insert into tags (tag_name) values ('Balanced');
insert into tags (tag_name) values ('hierarchy');
insert into tags (tag_name) values ('support');
insert into tags (tag_name) values ('Reactive');
insert into tags (tag_name) values ('Reverse-engineered');
insert into tags (tag_name) values ('Advanced');
insert into tags (tag_name) values ('Re-contextualized');
insert into tags (tag_name) values ('product');
insert into tags (tag_name) values ('homogeneous');
insert into tags (tag_name) values ('Innovative');
insert into tags (tag_name) values ('mission-critical');
insert into tags (tag_name) values ('Robust');
insert into tags (tag_name) values ('logistical');
insert into tags (tag_name) values ('time-frame');
insert into tags (tag_name) values ('capacity');
