insert into test_strings (regex_id, test_string) values (1, 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into test_strings (regex_id, test_string) values (2, 'est phasellus sit amet erat nulla tempus vivamus in felis');
insert into test_strings (regex_id, test_string) values (3, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi');
insert into test_strings (regex_id, test_string) values (4, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae');
insert into test_strings (regex_id, test_string) values (5, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et');
insert into test_strings (regex_id, test_string) values (6, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien');
insert into test_strings (regex_id, test_string) values (7, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate');
insert into test_strings (regex_id, test_string) values (8, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum');
insert into test_strings (regex_id, test_string) values (9, 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat');
insert into test_strings (regex_id, test_string) values (10, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem');
insert into test_strings (regex_id, test_string) values (11, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar');
insert into test_strings (regex_id, test_string) values (12, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into test_strings (regex_id, test_string) values (13, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit');
insert into test_strings (regex_id, test_string) values (14, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into test_strings (regex_id, test_string) values (15, 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet');
insert into test_strings (regex_id, test_string) values (16, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse');
insert into test_strings (regex_id, test_string) values (17, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio');
insert into test_strings (regex_id, test_string) values (18, 'nulla sed accumsan felis ut at dolor quis odio consequat');
insert into test_strings (regex_id, test_string) values (19, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices');
insert into test_strings (regex_id, test_string) values (20, 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et');
