DROP TABLE IF EXISTS regexes CASCADE;

CREATE TABLE regexes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  notes VARCHAR(255),
  is_public BOOLEAN DEFAULT TRUE,
  date_created TIMESTAMP DEFAULT NOW(),
  date_edited TIMESTAMP DEFAULT NOW()
);